### ISSUE TITLE
Cracked

### ISSUE THREAD

**Issue by LegitSoulja** [Didstopia/rust-server#10]
How would I make this so that I people can join with a cracked client?

I've setup Luma, and set server.secure to 0. When they join, they get kicked for steam auth.

Any work around? Rust 197.. latest

**Comment by LegitSoulja** [comment]
Actually I'm on the latest version of rust. 197

**Comment by Dids** [comment]
Cracked servers are not supported.

**Comment by LegitSoulja** [comment]
@Dids not for this, but in general how?

**Comment by LegitSoulja** [comment]
Never mind bro, I got it working

**Comment by LegitSoulja** [comment]
Nvm, I got it working. Thanks.

**Comment by grabarz121** [comment]
Can you post your solution? I can't join my own LAN server, all time steam auth failed...

**Comment by Dids** [comment]
Locking this from further comments, since as mentioned before: cracked servers are not supported.
