### ISSUE TITLE
Rcon connect failure

### ISSUE THREAD

**Issue by sergiolaguens** [Didstopia/rust-server#108]
Hi, im trying to send to my container de next command and i receive an error

**sergio@xx:~$ docker exec MODIFICADO_X2 rcon say hello
RconApp::Relaying RCON command: say hello
RconApp::Error: Error: connect ECONNREFUSED 127.0.0.1:28016
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 28016
}**

I think it is because i configured my container for rcon port 28116 so can i change the connection port?? I tried with -p PORT and more but anything worked.

Thanks and regards.

**Comment by Hardcore-fs** [comment]
Same.....
They have changed how rust loads & runs.

during a restart of the rust program inside the container (rust updates/user restarts), the ports are NOT correctly shutdown  & the containerised version hangs at this library load. (port in use)

if you shut down docker  container THIS fixes the issue, but restarting rust  inside the container  (server restart/update)
FAILS


`Fallback handler could not load library /steamcmd/rust/RustDedicated_Data/Mono/libadvapi32.dll
Shutdown signal received
ShutdownApp::RCON connecting to server
ShutdownApp::RCON error: Error: connect ECONNREFUSED 127.0.0.1:28016
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 28016
}
`

**Comment by WeaselSauce** [comment]
I'm having a similar issue but a different failure message

`RconApp::Relaying RCON command: serverinfo
RconApp::Error: Error: Parse Error: Expected HTTP/
    at Socket.socketOnData (_http_client.js:474:22)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  bytesParsed: 0,
  code: 'HPE_INVALID_CONSTANT',
  reason: 'Expected HTTP/',
  rawPacket: <Buffer 88 02 03 e8>
}
`

**Comment by rkubik** [comment]
Also running into this issue. Even using the RCON web I am unable to connect:

```
 Connection was closed - Error 1006 
```
