### ISSUE TITLE
Server not showing inside History or Search Tab

### ISSUE THREAD

**Issue by ItzBen2810** [Didstopia/rust-server#116]
I created a Rust server with your docker container, but it doesn't show in the history or in the search tab. 
I have linked a YML file of[ docker-compose](https://pastebin.com/ST2R475L). Im sure that everything is set up correctly please don't hesitate to ask for more context. Looking forwarded for your response :)

 OS: Ubuntu 22.04
 Docker: 24.0.2

**Comment by ItzBen2810** [comment]
UPDATE: It seems that the ports are open, but I can't ping them RUST_SERVER_PORT: 28015 and RUST_SERVER_QUERYPORT: 28016. I find this odd since I thought that 28015 is the port you connect over

**Comment by PhoenixInDarkness** [comment]
From what I can see, the query port and rcon are set to receive requests on port 28016. This is possible if one of them is listening on TCP and the other on UDP. Do you have both options open in your firewall?

I am currently experiencing a similar issue. My server is not showing up in the server history and is not being detected by gamemonitoring. I have decided to specify the following ports:

Game Port: 28015
Query Port: 28016
Rcon Port: 28017
Rust+ Port: 28082


Did you find a solution to the problem?

**Comment by ItzBen2810** [comment]
> From what I can see, the query port and rcon are set to receive requests on port 28016. This is possible if one of them is listening on TCP and the other on UDP. Do you have both options open in your firewall?
> 
> I am currently experiencing a similar issue. My server is not showing up in the server history and is not being detected by gamemonitoring. I have decided to specify the following ports:
> 
> Game Port: 28015 Query Port: 28016 Rcon Port: 28017 Rust+ Port: 28082
> 
> Did you find a solution to the problem?

Well for testing purposes I currently do not have a firewall enabled so there shouldn't be a problem with that

**Comment by PhoenixInDarkness** [comment]
Explicitly specifying different ports for Query and Rcon resolved my issue. My server is now being displayed everywhere.
Game Port: 28015
Query Port: 28016
Rcon Port: 28017
Rust+ Port: 28082
![image](https://github.com/Didstopia/rust-server/assets/56961609/704e86fa-593e-4a59-a277-c011b2f1ccc7)

**Comment by ItzBen2810** [comment]
> Explicitly specifying different ports for Query and Rcon resolved my issue. My server is now being displayed everywhere. Game Port: 28015 Query Port: 28016 Rcon Port: 28017 Rust+ Port: 28082 ![image](https://user-images.githubusercontent.com/56961609/248302171-704e86fa-593e-4a59-a277-c011b2f1ccc7.png)

If you would have a look at the docker-compose file I have linked you will see Im literally have the same stuff as you. How will that help me fix my problem? I don't understand

**Comment by PhoenixInDarkness** [comment]
I'm sorry I didn't notice the file.
My server appeared in the list after opening port 28016/udp
try adding 
 ` - 28016:28016/udp`

My docker-compose file looks like this
![image](https://github.com/Didstopia/rust-server/assets/56961609/ca8e9d90-3a26-4201-a5c5-8b110bdde810)

**Comment by ItzBen2810** [comment]
> I'm sorry I didn't notice the file. My server appeared in the list after opening port 28016/udp try adding ` - 28016:28016/udp`
> 
> My docker-compose file looks like this ![image](https://user-images.githubusercontent.com/56961609/248321573-ca8e9d90-3a26-4201-a5c5-8b110bdde810.png)

Thanks I can now see it in history but not in browser tab why is that?

**Comment by b33slayer** [comment]
8080 tcp - web rcon port
28015 udp - game port
28016 tcp - rcon port 
28017 udp - query port for server
28082 tcp - app port rust+

**Comment by ItzBen2810** [comment]
> 8080 tcp - web rcon 28015 udp - game port 28016 tcp - rcon porn 28017 udp - query port for server 28082 tcp - app port rust+
