### ISSUE TITLE
Players Cannot Join | The Object you want to instantiate is null EnvironmentFishManager.GenerateFish

### ISSUE THREAD

**Issue by willcurry** [Didstopia/rust-server#117]
**Describe the bug**
No players can join. When joining this error is pasted to console and a similar to the client (image below).
wilton disconnecting: Exception (cs:83553): ArgumentException: The Object you want to instantiate is null. UnityEngine.Object.CheckNullArgument (System.Object arg, System.String message) (at <00000000000000000000000000000000>:0) UnityEngine.Object.Instantiate[T] (T original) (at <00000000000000000000000000000000>:0) EnvironmentFishManager.GenerateFish () (at <00000000000000000000000000000000>:0) 

I am running 0 mods. Oxide is disabled. The only changes are to the ports the server is running on. 

Here is my env file: 
![image](https://github.com/Didstopia/rust-server/assets/11460313/b1dacda3-a4a3-46d9-8ff8-00037e00f01d)

And here is how I run the docker image: 
`docker run --name rust-server -d -m 8g --cpus="1" -p 28011:28011 -p 28011:28011/udp -p 28012:28012 -p 8080:8080 -v /rust:/steamcmd/rust --env-file rust.env didstopia/rust-server`

**To Reproduce**
Setup a server using the given tutorial and same environment.

**Expected behavior**
Server should allow players to join.

**Screenshots**
![image](https://github.com/Didstopia/rust-server/assets/11460313/1dc379d3-468c-4346-8c98-9a5ce4110c42)

**Environment (please complete the following information):**
 - OS: Debian 11 | 5.10.0.16-amd64 kernal
 - Docker: 24.0.2

**Comment by ItzBen2810** [comment]
Why is there a minus behind the RUST_APP_PORT? That doesn't seem right

**Comment by willcurry** [comment]
> Why is there a minus behind the RUST_APP_PORT? That doesn't seem right

Because thats how you disable the companion app from command line as stated in the wiki. I have tried removing that and it still does not work though.

**Comment by willcurry** [comment]
I have no clue whats different but it is now working. With the exact same config and setup. I did notice my environment variables stopped updating when re-creating containers with the same name. Creating containers with new names (same .env file) seemed to fix this. I am new to Docker and not sure if it was caching the file or something...
