### ISSUE TITLE
steamcmd does not install on first docker run (no config)

### ISSUE THREAD

**Issue by timelf123** [Didstopia/rust-server#12]
first run:
`docker run --name rust-server didstopia/rust-server`

```
Installing/updating Rust.. (this might take a while, be patient)
Starting web server..
Log rotation enabled!
Using startup arguments: -batchmode -load +server.secure 1
Cleaning up old logs..
mv: cannot stat '/steamcmd/rust/logs/*.txt': No such file or directory
Starting scheduled task manager..
Starting Rust..
couldn't execute "/steamcmd/rust/RustDedicated": no such file or directory
    while executing
"spawn -noecho /steamcmd/rust/RustDedicated -batchmode -load +server.secure 1 +rcon.port 28016 +rcon.password docker +rcon.web 1 -logfile /dev/stdout +..."
    ("eval" body line 1)
    invoked from within
"eval [list spawn -noecho] $argv"
    invoked from within
"if {[string compare [lindex $argv 0] "-p"] == 0} {
    # pipeline
    set stty_init "-echo"
    eval [list spawn -noecho] [lrange $argv 1 end]
    clo..."
    (file "/usr/bin/unbuffer" line 13)
```

I'm guessing because the volume isn't linked yet? Anyway, the container works great under an Ubuntu host once you pass it all the required options and link a volume.

May be unrelated - but on a Windows host the installer never seems to be able to copy the files from the `steamapps/downloading` folder to the root of the volume - failing with the same `couldn't execute "/steamcmd/rust/RustDedicated": no such file or directory`

**Comment by Dids** [comment]
Did you try it again after that? I just tried it without mounting a volume, and it worked (macOS here), up to a point.

There's definitely a bug regarding not mounting a volume, but I'll open a separate issue on that. It installs and starts fine, just crashes at the very end.

I'll have a look if supporting Windows is possible and get back to you on that.

**Comment by Dids** [comment]
Opened #13 for the volume issue and #14 for Windows support. I'll keep this one open until both of those are resolved, or if I need more information from you. :)

**Comment by timelf123** [comment]
> Did you try it again after that?
Everything worked great after mounting a volume on a nix host, thanks!

**Comment by timelf123** [comment]
Feel free to ping me on #13 or #14 - closing this as a nonissue since no one will use this without a volume 👍

**Comment by dakkafex** [comment]
trying to use the first start command but i also get "couldn't execute "/steamcmd/rust/RustDedicated": no such file or directory
    while executing"

**Comment by Dids** [comment]
@dakkafex It's only an issue if you're not (correctly) mounting a volume, or if there was an issue installing the Rust server via steamcmd.

**Comment by Sloth-on-meth** [comment]
still an issue
