### ISSUE TITLE
Add wipe command

### ISSUE THREAD

**Issue by timelf123** [Didstopia/rust-server#15]
Not sure if this is better suited to the host or not but the script could look something like
```
#/bin/bash
serveridentitydir="/steamcmd/rust/server/${RUST_SERVER_IDENTITY}"
find "${serveridentitydir:?}" -type f -name "proceduralmap.*.sav" -delete
find "${serveridentitydir:?}" -type f -name "proceduralmap.*.map" -delete
rm -rf "${serveridentitydir:?}/user"
rm -rf "${serveridentitydir:?}/storage"
find "${serveridentitydir:?}" -type f -name "Log.*.txt" -delete
```

PS - great work on this container!

**Comment by predominant** [comment]
Thinking more on this. The process would be:

* Announce shutdown (optional)
* Shutdown
* Backup (optional)
* Wipe
* Start (inc. update etc, as normal)

**Comment by predominant** [comment]
Also, wondering if we can link all the required files into a separate volume that would represent each save, incase you wanted to load/unload that volume instead of actually destroying files.

The resulting operation would replace "Backup" and "Wipe" operations above, with "create new volume", and "run with new volume for saves only".

**Comment by LordRofl** [comment]
When this come, it should now support Mapwipe with/out Blueprintwipe.

**Comment by predominant** [comment]
Thats a good point @LordRofl - Thanks for the feedback.

**Comment by andrewmueller1** [comment]
This would still be a nice to have

**Comment by ervins0x** [comment]
BUMP, agree that this would be really nice, love that ticket is still open from 2017 🥶

**Comment by timelf123** [comment]
> BUMP, agree that this would be really nice, love that ticket is still open from 2017 🥶

The ticket is closed and I provided most of the code to do this feature. Feel free to finish it yourself :)
