### ISSUE TITLE
Run as non-root

### ISSUE THREAD

**Issue by Dids** [Didstopia/rust-server#17]
Run Rust and other services as a non-root user, if possible. Be sure to avoid/catch any UID issues on the host system when working with volumes, since that used to be an issue, so might still be too.

Also look into possibly setting the user/UID/GID via environment variables.

**Comment by timelf123** [comment]
Most of the linuxserver.io containers have id/guid bit setting examples if you need a reference point

**Comment by Dids** [comment]
Fixed in https://github.com/Didstopia/rust-server/commit/ad95963134a412dd03214cf512964154b733e045
