### ISSUE TITLE
Autoupdate function kills container

### ISSUE THREAD

**Issue by LordRofl** [Didstopia/rust-server#19]
### Environment (OS/Distro, Docker version etc.)
Ubuntu 16.04

Today after a rustupdate, the server seems to detect the update and kicks all and shutdown (quit)
But after not comming back online i saw that the dockercontainer was stopped and i had to manually start it again.

Some Logs:
...
xxx/76561198282330729/☢Blitzz☢ kicked: Kicked: No Reason Given
xxx/76561198177009247/AzokCz kicked: Kicked: No Reason Given
Invalidate Network Cache took 0.02 seconds
Saved 67,268 ents, serialization(0.00), write(0.01), disk(0.00) totalstall(0.03).
Saving complete
Config Saved
[Raknet] Server Shutting Down (quit)
Exiting..

**Comment by predominant** [comment]
Are you using the latest tag?

**Comment by LordRofl** [comment]
shure!

**Comment by timelf123** [comment]
set your container to restart=always or unless-stopped

**Comment by MattPark** [comment]
Yes, that's working fine it just restarts the container 10-15 times a day.  I can't figure out the pattern.  Not maxing out on ram or gpu either

**Comment by LordRofl** [comment]
It works with parameter --restart=always in docker run command. Thank you, this can be closed. But you should mention it in your Installinstructions.
