### ISSUE TITLE
Log Rotation

### ISSUE THREAD

**Issue by Dids** [Didstopia/rust-server#2]
Add log rotation/archiving with configurable parameters.

**Comment by Dids** [comment]
This still needs cleanup functionality, but should be easy enough with find and mtime.

**Comment by cgarnier** [comment]
Hello,
I dont understand where are the logs. There nothing more accurate then the text files in the server log folder ?

**Comment by Dids** [comment]
Not sure what you mean? All the logs that Rust provides are being outputted to a single log file.
