### ISSUE TITLE
Reread Environmentfile with every serverstart

### ISSUE THREAD

**Issue by LordRofl** [Didstopia/rust-server#22]
It would be nice when the Container reread the env file when starting up again. That makes it easier to adjust Settings on the fly without stopping and deleting the container.

**Comment by predominant** [comment]
Which environment variables are you changing? Just keen to know.

**Comment by LordRofl** [comment]
Servername for example. But after rethinking about that i guess its not possible with docker.

**Comment by predominant** [comment]
I also think servername isn't something that is likely to change often once you're setup.

**Comment by timelf123** [comment]
Lot's of servers change names when wiping if not using the Oxide plugin that does it

**Comment by blacklabelops** [comment]
I do this with server seed. So i support this request

**Comment by ba0f3** [comment]
this is how I did https://github.com/ba0f3/rust-server/blob/master/start_rust.sh#L5-L11

**Comment by timelf123** [comment]
can you PR that change @ba0f3 it LGTM

**Comment by predominant** [comment]
Absolutely, send a PR, it would be nice to attribute this change to you @ba0f3

**Comment by Dids** [comment]
LGTM

**Comment by LordRofl** [comment]
No PR yet? Will you add this then instead?
