### ISSUE TITLE
Strange behavior with Oxide enabled

### ISSUE THREAD

**Issue by LordRofl** [Didstopia/rust-server#23]
Hello,

when iam using oxide enabled 1 then all files get owned by id 1000. Normally the user is root when oxide disabled.

**Comment by Dids** [comment]
Use `PUID=0` and `PGID=0` environment variables to forcibly use the `root` user.
For security reasons, the image defaults to a regular user (user id 1000, group id 1000), but this can be overridden to point at any local (host-side) user.

**Comment by predominant** [comment]
I think we can close this.

**Comment by LordRofl** [comment]
Wait, yea shure but why this only take effect when enabling oxide?

**Comment by Dids** [comment]
Sorry, just realized I might know what's going on, if it's really only with Oxide enabled. Having a look now and will let you know as soon as I have an update.

**Comment by Dids** [comment]
Should be fixed now, so just pull the new version and try it out. :)
