### ISSUE TITLE
Error while compiling: compiler v0.0.0.0 disconnected

### ISSUE THREAD

**Issue by ghost** [Didstopia/rust-server#25]
### Environment (OS/Distro, Docker version etc.)
Ubuntu 16.04, Docker 17.12.0-ce

```
sudo docker run -it --name rust-server -d -p 28015:28015 -p 28015:28015/udp -p 28016:28016 -p 8080:8080 -v /opt/rust:/steamcmd/rust --env-file /etc/rustserver/rust.env --restart unless-stopped didstopia/rust-server
```

### Expected behavior
Plugins are compiled and load normally/consistently

### Actual behavior
Randomly plugins stop being compiled and loaded when added to the server, requiring a restart of the server. Will work fine for a while but after a number of plugins are compiled/loaded the compiler "disconnects".

```
Running dependency trace for CSharpCompiler.x86_x64
User running server may not have the proper permissions or install is missing files
Error while compiling: compiler v0.0.0.0 disconnected
```

### Steps to reproduce
Load plugin .cs files one at a time until the compiler fails.

**Comment by Dids** [comment]
Is this still an issue? I'm wondering if it's more of an issue with Oxide?

**Comment by torarnv** [comment]
I'm still seeing this.
