### ISSUE TITLE
Enable SSL with LetsEncrypt to webrcon?

### ISSUE THREAD

**Issue by ghost** [Didstopia/rust-server#26]
Would be an awesome addition to protect the webrcon page with LetsEncrypt via nginx :)

**Comment by Steven-Harris** [comment]
@term1nal, you could easily setup a let-encrypt proxy to do this. That's what I have done. Here is a great one to use [https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion) also linuxserver.io's letencrypt container is great too

**Comment by Dids** [comment]
The biggest issue I've had with SSL and webrcon is that their implementation doesn't seem to support SSL at all (eg. no `wss://` protocol support), at least not when I last checked.
