### ISSUE TITLE
Docker  rust-server in Virtualbox

### ISSUE THREAD

**Issue by earth2016** [Didstopia/rust-server#28]
Hi Guys,

I want to launch rust-server in dockerized environment but using Virtualbox.

When i run the image

docker run --name rust-server1 \
	-p 3000:3000 -p 8080:8080 -p 28015:28015 -p 28016:28016 \
	-it -d \
	-v /mnt/sda1/var/game/RustServer:/steamcmd/rust \
	--env RUST_SERVER_WORLDSIZE=1500 \
	didstopia/rust-server

I finally have this error message

> NullReferenceException: Object reference not set to an instance of an object
>   at TerrainMap`1[T].FromByteArray (System.Byte[] dat) [0x00000] in <be71cdfc10ca49569e8d5f7ec78e6fbc>:0 
>   at WorldSetup+<InitCoroutine>c__Iterator0.MoveNext () [0x00594] in <be71cdfc10ca49569e8d5f7ec78e6fbc>:0 
>   at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00027] in <3d3ce0a05f164357836ebcee3caff781>:0 

This error i don't know how to fix it. i think the docker binaries should be the host not inside a virtualmachine (docker-machine i used to create the docker binaries and then i run the docker didstopia/rust-server image.

**Comment by Dids** [comment]
Try without the volume mount (`-v ...` parameter) to see if it'll work. That does sound like a Rust issue and not related to the Docker image itself, but it definitely could be the environment that's causing it.

So you've setup a virtualbox VM and installed Docker there?

**Comment by earth2016** [comment]
@Dids Thanks for the  reply!

I haven't setup VB, i have used docker-machine (it is easier) to create a virtualmachine with the docker binaries. I connect to it and i run the command of docker previously commented out.

**Comment by earth2016** [comment]
I will try it without vbox. Regards \o

**Comment by Dids** [comment]
Sounds like a network issue unrelated to this image, yeah. Is it okay to close this issue?
