### ISSUE TITLE
Fully automatic updates

### ISSUE THREAD

**Issue by Dids** [Didstopia/rust-server#3]
Add fully automatic updates, including querying Steam for periodically, notifying players about an update, restarting the server and installing the updates.

**Comment by Dids** [comment]
This is technically already a part of the image, but as it's not working 100% reliably yet, it's not documented.

**Comment by JDog1895** [comment]
Here is my try to get the Version of rust dedicated server:
echo -e "\0\0\0\0TSource Engine Query\0" | nc -u -q 1 IP-Adress rcon-port | tr '[\000-\011\013-\037\177-\377]' '.' | sed 's/\(.*\)\(,cp\)\([0-9]*\)\(,v\)\([0-9]*\)\(.*\)/\5/'`

But now, I dont know a way to check this on an offical server.

Also its recommended to check the log.log-file, because not every update changes the version of rust.

Hope i could help a lil bit.

**Comment by Dids** [comment]
Thanks for that!

I'm currently fetching the build id directly from Steam, but they also include a unix timestamp for each build, so I might be able to switch to using the timestamp as well, meaning that even if the build id didn't change, the timestamp would, and it would trigger an update.

**Comment by JDog1895** [comment]
That would be great. I hope that's the right way to do it.

**Comment by cgarnier** [comment]
It s updating too fast. Each time, players cant reconnect to the server because steam is late.
Is threre a way to wait the client update is available before updating the server ?

**Comment by Dids** [comment]
I'll see if I can plug into whenisupdate.com API, so once it says the client update is out, it'll trigger the update.

**Comment by Dids** [comment]
Alright, this is done now. Just pull the latest image, and it should be all good.

**Comment by cgarnier** [comment]
Ty, you awesome =)

**Comment by Dids** [comment]
No problem! If you run into any issues with it in the future, just comment here and I'll take a look asap. :)

**Comment by cgarnier** [comment]
It didnt worked.The server didnt update by its own this night.

**Comment by Dids** [comment]
I know, I'm sorry. Just saw this happen on my own server too. :(
Looking into it, it worked fine when I tested it before.

**Comment by Dids** [comment]
@cgarnier Found the issue, pushing a fix now!

**Comment by Dids** [comment]
Reopening. While this works, it doesn't warn the users and doesn't provide any information in the kick message.

**Comment by cgarnier** [comment]
Time to see if it will works =)

**Comment by Dids** [comment]
Closing, since it looks like this is working as intended.
