### ISSUE TITLE
cannot install on linux

### ISSUE THREAD

**Issue by Hardcore-fs** [Didstopia/rust-server#35]
the directory /steamcmd/rust  exists in the  root directory of the server & has been set to allow  everybody R/W access (for testing)

docker run --name rust-server -d -p 28015:28015 -p 28015:28015/udp -p 28016:28016 -p 8080:8080 -v /rust:/steamcmd/rust --env-file /rust.env didstopia/rust-server

sudo docker logs -f rust-server

Loading Steam API...OK.
@sSteamCmdForcePlatformType linux
"@sSteamCmdForcePlatformType" = "linux"

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
force_install_dir /steamcmd/rust
app_info_update 1
app_update 258550 validate
ERROR! Failed to install app '258550' (Disk write failure)
quit
Starting web server..
Log rotation disabled!
Starting scheduled task manager..
Starting Rust..
./start.sh: line 222: /steamcmd/rust/RustDedicated: No such file or directory
Exiting..

**Comment by Dids** [comment]
You said that `/steamcmd/rust` exists on the server, you mean the host system? If this is the case, you should actually be using `/rust` on the host server, as `/steamcmd/rust` is that path inside the actual container. The volume mount argument is basically like this: `-v <host_path>:/<container_path>`.

**Comment by Hardcore-fs** [comment]
Hi,
yes under linux on the docker "host", I have a mount point /directory  called "/steamcmd/rust"
there is also a root directory on the host created called "/rust"

so theoretically it might be (if not confusing)

-v /steamcmd/rust:/steamcmd/rust

which should use the internal container mount point "/steamcmd/rust" as the host mount point "/steamcmd/rust"

if this is the case then i already have a root directory outside the container on the HOST called "/rust"

why the command fails, since "/steamcmd/rust" inside the container should mount to "/rust" on the host with a command of "-v /rust:/steamcmd/rust " 
but it is throwing an error.
note without the  "-v" command everything functions correctly without error

**Comment by Hardcore-fs** [comment]
ok got it, but needed to make some changes

sudo docker run --name rust-server -d -p 28015:28015 -p 28015:28015/udp -p 28016:28016 -p 8080:8080 --mount 'type=bind,source=/rustdata,target=/steamcmd/rust' --env-file /rust.env didstopia/rust-server

**Comment by Hardcore-fs** [comment]
might have been due to the version of "docker" on the linux os
some RH  installs use a very old version...like 1.3
