### ISSUE TITLE
latest update does nto seem to be updating the internal rust copy

### ISSUE THREAD

**Issue by Hardcore-fs** [Didstopia/rust-server#38]
client fails saying server requires update.

the new 209 update

sudo docker run --name rust-server -d -p 28015:28015 -p 28015:28015/udp -p 28016:28016 -p 8080:8080 --mount 'type=bind,source=/rustdata,target=/steamcmd/rust' --env-file /rustdata/rust.env -ti didstopia/rust-server start

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
force_install_dir /steamcmd/rust
app_info_update 1
app_update 258550 validate
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
Error! App '258550' state is 0x206 after update job.
quit

**Comment by Hardcore-fs** [comment]
ok....
basically if the "rust" update fails due to space or other reason, the script continues & launches old version of the app, which then goes on to error.

**Comment by Hardcore-fs** [comment]
It took a bit of cleaning up. but yes it can almost self recover,
I had the container using a separate disk.

if the update fails, the rust server startup process should be stopped, because:
1. the clients are auto updated by rust, they won't run against a server that is a revision behind
2.The restarted server is an old version that complains the clients are ahead of it in revision.

so from the outside everything looks ok, the rcon works and the rust server is up, but clients fail because the update failed.



 it seems to need about 20GB free:
6gb*2 (old & update)+6GB for map save files

So maybe a return check for errors on the update  & halt for user intervention.
Since starting a rust server is a non-trivial time process.

**Comment by Dids** [comment]
Pushing a fix for this now, which should just terminate if the install/update fails for any reason.
