### ISSUE TITLE
Env variable to set map size?

### ISSUE THREAD

**Issue by kevzettler** [Didstopia/rust-server#4]
Not seeing an ENV variable to set map size in configuration lists in any of the docs

**Comment by Dids** [comment]
You can append it to the `RUST_SERVER_STARTUP_ARGUMENTS`, ie. `RUST_SERVER_STARTUP_ARGUMENTS="-batchmode -load -logfile /dev/stdout +server.secure 1 +server.worldsize 4000"`.

I guess it would make more sense to have at least the most common variables as separate env vars, huh?

**Comment by kevzettler** [comment]
> I guess it would make more sense to have at least the most common variables as separate env vars, huh?

Yeah keeps it consistent and expected.

I would suggest all these as env variables https://developer.valvesoftware.com/wiki/Rust_Dedicated_Server#Configuration_.26_running

Other than that. Great work. this is a really impressive project and great example of an excellent Dockerized application. It's brain-dead simple to setup.

**Comment by Dids** [comment]
Fixed in https://github.com/Didstopia/rust-server/pull/9.
