### ISSUE TITLE
Replace oxide with umod

### ISSUE THREAD

**Issue by brantje** [Didstopia/rust-server#42]
**Is your feature request related to a problem? Please describe.**
Oxide mod is deprecated
**Describe the solution you'd like**
Would be nice if it's replaced with [umod](https://umod.org/)

**Comment by Josh5K** [comment]
I think Oxide's repo was just renamed to umod and from the looks of the start-up script the url used for updating oxide/umod redirects to https://api.github.com/repositories/94599577/releases/latest which will get the newest version of umod.

I haven't had a chance to try this out but it looks like it will continue to work.

**Comment by LsHallo** [comment]
See pull request #45****

**Comment by Dids** [comment]
Merged #45.
