### ISSUE TITLE
RCON restart command kills the server

### ISSUE THREAD

**Issue by duckman** [Didstopia/rust-server#43]
**Describe the bug**
When we initiate a restart using the rcon command, the server shuts down gracefully, but never starts back up and I have to start the docker container again.

**To Reproduce**
1. Go to web rcon or any other rcon method
2. Type 'restart' into console
3. Rust does it's thing and then shuts down

**Expected behavior**
The docker container shouldn't stop and the server should start back up

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04.2 LTS
 - Docker: Docker version 17.05.0-ce, build 89658be

**Comment by Dids** [comment]
You can use a restart policy for the container instead: https://docs.docker.com/config/containers/start-containers-automatically/
