### ISSUE TITLE
seeing a lot more console output after recent changes

### ISSUE THREAD

**Issue by Hardcore-fs** [Didstopia/rust-server#44]
seeing the following errors after updating to latest docker image

Even though everything seems to get setup correctly.

Command Line: "/steamcmd/rust/RustDedicated" "-batchmode" "-load" "-logfile" "/dev/stdout" "+server.secure" "1" "+rcon.port" "28016" "+rcon.password" "******" "+rcon.web" "1" "+server.identity" "zzzzzzzzzz" "+server.seed" "6549" "+server.hostname" "Razors_Edge" "+server.url" """" "+server.headerimage" """" "+server.description" "This is a TEST server ONLY. You can join but there is no save state" "+server.worldsize" "4000" "+server.maxplayers" "4" "+server.saveinterval" "600" 
Command 'batchmode' not found
Command 'load' not found
Command 'logfile' not found
server.secure: "True"
rcon.port: "28016"
Command 'rcon.password' not found
rcon.web: "True"
server.identity: "xxxx"
server.seed: "6549"
server.hostname: "xxxxxxxx"
server.url: "1"
server.headerimage: "1"
server.description: "This is a TEST server ONLY. You can join but there is no save state"
server.worldsize: "4000"
server.maxplayers: "4"
server.saveinterval: "600"

**Comment by Dids** [comment]
These are a feature and not a bug, also not related to the Docker image. The developers have stated that these can be safely ignored, along with a few other warnings that can appear on startup.

**Comment by Dids** [comment]
Also to answer why you're seeing more output now: the latest image outputs both stdout and stderr, and I believe it only showed stdout before, while putting stderr in the log files.

**Comment by Hardcore-fs** [comment]
ok thanks for your help
