### ISSUE TITLE
may need an update to latest files

### ISSUE THREAD

**Issue by Hardcore-fs** [Didstopia/rust-server#54]
can we get a refresh on the  container build objects for hte os for security.. thanks.

**Comment by Dids** [comment]
Updating the container today. The base images are automatically kept up to date, and I recently made several improvements to them. I'm also upgrading this container to use Ubuntu 18.04 with Node.js v12.

**Comment by Dids** [comment]
Done.

**Comment by Hardcore-fs** [comment]
Yep the main issue is the embedded Linux for security....

I find that if i fire up a console link into the container   
then  i can manually update packages... so the internal linux stuff is not always updating.

**Comment by Dids** [comment]
It is now. I've setup Docker Hub to automatically update this image when the base image updates, which should also happen automatically.

**Comment by Hardcore-fs** [comment]
Excellent.....
