### ISSUE TITLE
Image does not run on arm architecture

### ISSUE THREAD

**Issue by Algatux** [Didstopia/rust-server#55]
I am having issues running the container on a raspberry pi 4, getting the error "standard_init_linux.go:211: exec user process caused "exec format error"

Any suggestion on how to build a working image for arm64 ?

**Comment by Dids** [comment]
As far as I'm aware, neither the Rust server or the Steam binary will run on ARM (Steam might, not sure though). I don't have the hardware (or the time) to test though.

**Comment by predominant** [comment]
The `steamcmd` utility is a 32bit binary compiled for x86, and is compatible with x86_64 when using multiarch support on your Linux distro.

ARM is completely different, and steam does not currently offer an ARM build.
