### ISSUE TITLE
nginx faulting/crashing

### ISSUE THREAD

**Issue by Xilvaro** [Didstopia/rust-server#56]
I have an fresh Docker install, previously this Rust server was running like a charm, however when I start the container now I get this message after downloading/starting (and the container stops):

Loading Prefab Bundle 0%
Loading Prefab Bundle 0%
Loading Prefab Bundle 0%
Loading Prefab Bundle 0%
Loading Prefab Bundle 0%
Loading Prefab Bundle 0%
+ pkill -f nginx

.
+ echo Exiting..
+ exit

Anyone got a clue?

**Comment by Dids** [comment]
I definitely more logs/information than this to go on. I haven't seen this issue and this is the first report I've heard of it so far.

**Comment by Dids** [comment]
Never mind, I'm able to replicate this now!

**Comment by Dids** [comment]
Okay, I've figured it out and it's unfortunately out of my control.

Recent changes to the procgen require more memory than previously, so for example 4GB of RAM is not enough anymore (this is what I usually test with).
I removed the memory limit from Docker, and it generated the map and started the server just fine.
