### ISSUE TITLE
Run as non root group

### ISSUE THREAD

**Issue by Fizcko** [Didstopia/rust-server#57]
Hi,

To manage rights on data persistence into the host can you change the following command in the startup script :

start_rust.sh : L60
```
# Fix ownership
chown -R $(whoami):$(id -g) /steamcmd/rust
```

For a normal usage this will not change the way of using of the container but for an advanced usage it would be great.

**Comment by Fizcko** [comment]
What did you thinks about this request @Dids ?

**Comment by Dids** [comment]
Fixed in https://github.com/Didstopia/rust-server/commit/ad95963134a412dd03214cf512964154b733e045
