### ISSUE TITLE
"Error! Timed out waiting for AppInfo update."

### ISSUE THREAD

**Issue by t3pfaffe** [Didstopia/rust-server#58]
**Describe the bug**
Crashing on attempt to install

**To Reproduce**
Attempt to run 1 instance of this image

**Expected behavior**
A crash does not occur and rust server is successfully installed and running. 

**Environment (please complete the following information):**
 - OS: [RancherOS v1.5.3]
 - Rancher 4.14.128
 - Kublet v1.14.3
 - Docker: 18.6.6

**Additional context**
Full logs before crash: 
[crashlog.txt](https://github.com/Didstopia/rust-server/files/4142263/crashlog.txt)

**Comment by Dids** [comment]
Sounds like a network issue. Keep trying and it should successfully download it, unless your container has no networking to begin with.
