### ISSUE TITLE
still a server startup failure

### ISSUE THREAD

**Issue by Hardcore-fs** [Didstopia/rust-server#60]
Complete re-install on cent os7

set directory path & rights

chown -R 1000:1000 /rustdata

updated docker container
docker pull didstopia/rust-server

started container
sudo docker run --name 4000_40755 -d -p 28015:28015 -p 28015:28015/udp -p 28016:28016 -p 8080:8080 --mount 'type=bind,source=/rustdata,target=/steamcmd/rust' --env-file /rustdata/rust.env didstopia/rust-server

sudo docker logs -f  4000_40755
..lots of update & startup stuff
`Downloading and installing latest Oxide..
x RustDedicated_Data/
x RustDedicated_Data/Managed/
x RustDedicated_Data/Managed/Assembly-CSharp.dll
x RustDedicated_Data/Managed/Facepunch.Console.dll
x RustDedicated_Data/Managed/Facepunch.Network.dll
x RustDedicated_Data/Managed/Facepunch.Rcon.dll
x RustDedicated_Data/Managed/Mono.Data.Tds.dll
x RustDedicated_Data/Managed/MySql.Data.dll
x RustDedicated_Data/Managed/NewAssembly.dll
x RustDedicated_Data/Managed/Oxide.Core.dll
x RustDedicated_Data/Managed/Oxide.CSharp.dll
x RustDedicated_Data/Managed/Oxide.MySql.dll
x RustDedicated_Data/Managed/Oxide.References.dll
x RustDedicated_Data/Managed/Oxide.Rust.dll
x RustDedicated_Data/Managed/Oxide.SQLite.dll
x RustDedicated_Data/Managed/Oxide.Unity.dll
x RustDedicated_Data/Managed/System.Configuration.Install.dll
x RustDedicated_Data/Managed/System.Data.dll
x RustDedicated_Data/Managed/System.Data.SQLite.dll
x RustDedicated_Data/Managed/System.Drawing.dll
x RustDedicated_Data/Managed/System.Runtime.Serialization.dll
x RustDedicated_Data/Managed/System.Transactions.dll
x RustDedicated_Data/Managed/x64/
x RustDedicated_Data/Managed/x64/libmonoboehm-2.0.so.1
x RustDedicated_Data/Managed/x64/libMonoPosixHelper.so
x RustDedicated_Data/Managed/x64/libsqlite3
x RustDedicated_Data/Managed/x64/libsqlite3.so
x RustDedicated_Data/Managed/x64/sqlite3.dll
x RustDedicated_Data/Managed/x86/
x RustDedicated_Data/Managed/x86/libmonoboehm-2.0.so.1
x RustDedicated_Data/Managed/x86/libMonoPosixHelper.so
x RustDedicated_Data/Managed/x86/libsqlite3
x RustDedicated_Data/Managed/x86/libsqlite3.so
x RustDedicated_Data/Managed/x86/mono-2.0.dll
x RustDedicated_Data/Managed/x86/msvcp140.dll
x RustDedicated_Data/Managed/x86/msvcr120.dll
x RustDedicated_Data/Managed/x86/sqlite3.dll

**chmod: changing permissions of '/dev/null': Operation not permitted
Starting web server..
Log rotation disabled!
Starting Rust..
Found path: /steamcmd/rust/RustDedicated
Unable to open log file, exiting.
Exiting..
`
server refuses to startup correctly.**

rollingback to   previous update of  
" didstopia/rust-server"   before   non root user changes , it functions correctly

`x RustDedicated_Data/Managed/x86/sqlite3.dll
Starting web server..
Log rotation disabled!
Starting scheduled task manager..
Starting Rust..
Found path: /steamcmd/rust/RustDedicated
Mono path[0] = '/steamcmd/rust/RustDedicated_Data/Managed'
Mono config path = '/steamcmd/rust/RustDedicated_Data/MonoBleedingEdge/etc'
Preloaded 'libRakNet.so'
Preloaded 'libRustNative.so'
`
so it is clearly the last update breaking it.....

**Comment by Hardcore-fs** [comment]
OK.. found it......
if the linked path already contains logfiles etc, then they don't need to be re-made..
but if tehy don't exist AND  if you run the docker with "SUDO", then the docker code is running with admin rights....
But the internal container is 1000:1000
any New files in hte external OS get MADE AS the SYSTEM admin...... (maybe a priv esc?)
so the files external to the container get stamped as "root", and prevent the internal 1000:1000 user accessing them.

This is because the files were created AFTER  the command:
chown -R 1000:1000 /rustdata

looks like the "docker image" should have a check for how the docker is running & if it is root.. then shut it down & throw it back before files are created...

**Comment by Hardcore-fs** [comment]
OK found it.........

Since it now all runs as a low priv user

if you have any 
"RUST_SERVER_STARTUP_ARGUMENTS -logfile xxxxx"
where it is piped to an output channel....
it's gonna halt....

**Comment by Dids** [comment]
There is currently no workaround this, except for using it without `-logfile /dev/stdout`, as when you do _not_ specify `-logfile`, it will log to both stdout and stderr regardless. Using `-logfile /dev/null` will work with the next version, as there are checks for that.
Just to reiterate, the non-root user can write to `/dev/stdout` just fine, but for some reason Unity (Rust) fails to open it as a "log file".

Additionally, the next version will have permission fixes in the upstream (base images), which should always work, so long as Docker has the ability to manage the permissions.
It is also worth noting that the container itself doesn't actually run as a non-root user, while the startup script does.

**Comment by Dids** [comment]
You should be able to pull the new version now.

**Comment by Hardcore-fs** [comment]
Yep .. i put it here for completeness... so others could find it.
It was becasue i was using an env file that is a year old....
