### ISSUE TITLE
on the latest container  strings not passing in?

### ISSUE THREAD

**Issue by Hardcore-fs** [Didstopia/rust-server#61]
when setting server names in the env file only the first word is displayed, even though the full string appears to be passed over in the startup command.

....server.description" "bob test some server description” "+server.worldsize" "3000" 

After further testing.. something funky appears to be going on.......

if you manually type the server name & description using "nano" on the console, it works
but if you copy & paste.. it seems to break, normally at the first "space" character.

Also is there a way we could have a file reference option so the string can be pulled from a file instead of making the  config file so messy

**Comment by Dids** [comment]
How does your env file look? You need to have double quotes for the texts and there are some cases where special characters break it, even on Rust's side.

**Comment by Hardcore-fs** [comment]
Actually double quotes are not needed.....
this is part of what I typed manually and works perfectly
`RUST_SERVER_DESCRIPTION=This is a TEST Server ONLY!!\n Testing Oxide\n`

it would only display upto "This" under the  online game chooser!!, 
Spent hours getting it working, since it requires bringing up a new container & full boot before it appears in the game chooser... (finally nailed it to copy & paste breaking it)

infact you have to be real careful with Quotes becasue when the command string is built in your scripts it is possible to "escape" the quotes

Secondly
RUST_SERVER_IDENTITY ...... is a KILLER!!!
since it forms the names of directories & log files, even with quotes around it.
perhaps it should be "stripped" of space & special characters, before being used

`RUST_SERVER_IDENTITY=server_001`
I have seen things like
`RUST_SERVER_IDENTITY=Players! VRS  ENV *PVP*`
creating havoic with directory structures & log files.
