### ISSUE TITLE
re-readable startup files

### ISSUE THREAD

**Issue by Hardcore-fs** [Didstopia/rust-server#63]
is it possible for the container to re-read the configuration file, so that the  container does not need to be rebuilt & rebound for small text changes to server names & description.

**Comment by Dids** [comment]
Not easily, no. The env file can't be re-read, but theoretically the image could have a way of doing this.
Right now you could use RCON to change the server name and description on the fly, or the built-in `rcon` binary that's included in the image. These of course wouldn't persist, unless you'd also change the env vars etc.

Also worth noting that I've been giving a full rewrite of this image a lot of thought, so features like this one might be added in that. I know that a lot of people would want, for example, dynamic server name/description, where something like the wipe date or player amount would automatically be updated in the texts.

**Comment by Hardcore-fs** [comment]
yep that would be really cool...
perhaps a different os? 
centos internally maybe... since it's not continually & trivially updated like the  Deb...?

My other bug report related to some serious issues on the server naming/description & i'm not the only person who has seen it.
finally got it sorted out . but it requires manually typing all the details into the config..
seems copy & paste is what breaks it.., even though when the details are passed into the rust server by your scripts it "looks" fine ..but it won't display on the  Game picking lists...
