### ISSUE TITLE
libadvapi32 not found

### ISSUE THREAD

**Issue by torarnv** [Didstopia/rust-server#67]
When connecting with the web based rcon:

```
Plugins: Couldn't open advapi32, error: advapi32: cannot open shared object file: No such file or directory
Fallback handler could not load library /steamcmd/rust/RustDedicated_Data/Mono/libadvapi32.dll
Fallback handler could not load library /steamcmd/rust/RustDedicated_Data/Mono/libadvapi32.dll.so
Fallback handler could not load library /steamcmd/rust/RustDedicated_Data/Mono/advapi32.dll
Fallback handler could not load library /steamcmd/rust/RustDedicated_Data/Mono/libadvapi32
Fallback handler could not load library /steamcmd/rust/RustDedicated_Data/Mono/libadvapi32.so
Fallback handler could not load library /steamcmd/rust/RustDedicated_Data/Mono/advapi32
Fallback handler could not load library /steamcmd/rust/RustDedicated_Data/Mono/libadvapi32.dll
Fallback handler could not load library /steamcmd/rust/RustDedicated_Data/Mono/libadvapi32.dll.so
Fallback handler could not load library /steamcmd/rust/RustDedicated_Data/Mono/libadvapi32.dll
Plugins: Couldn't open advapi32, error: advapi32: cannot open shared object file: No such file or directory
Fallback handler could not load library /steamcmd/rust/RustDedicated_Data/Mono/libadvapi32.dll
Fallback handler could not load library /steamcmd/rust/RustDedicated_Data/Mono/libadvapi32.dll.so
Fallback handler could not load library /steamcmd/rust/RustDedicated_Data/Mono/advapi32.dll
Fallback handler could not load library /steamcmd/rust/RustDedicated_Data/Mono/libadvapi32
Fallback handler could not load library /steamcmd/rust/RustDedicated_Data/Mono/libadvapi32.so
Fallback handler could not load library /steamcmd/rust/RustDedicated_Data/Mono/advapi32
Fallback handler could not load library /steamcmd/rust/RustDedicated_Data/Mono/libadvapi32.dll
Fallback handler could not load library /steamcmd/rust/RustDedicated_Data/Mono/libadvapi32.dll.so
Fallback handler could not load library /steamcmd/rust/RustDedicated_Data/Mono/libadvapi32.dll
```

**Comment by torarnv** [comment]
After increasing RAM for the macOS Docker VM to 4GB, and exposing the right ports, I can now connect to both the RCON web UI and the game itself, so these errors are not critical. Perhaps something to fix either way, or at least document?

**Comment by Hardcore-fs** [comment]
it is not the "docker", basically rust tries to load them before they have initialized, but have actually loaded...

**Comment by torarnv** [comment]
Thanks for the info about `libadvapi32`. Perhaps it should be added to a FAQ/troubleshooting section too? See https://github.com/Didstopia/rust-server/pull/68

Regarding ram usage, it seems to work fine with 4GB, at least for my single user mucking-around-with- build-mechanics use-case, but good to know!

**Comment by Hardcore-fs** [comment]
it can "work" on 2GB.. but "working" is not the issue.
OSX specializes in "swap" capability something they honed over  more than a decade.
Sadly it is system volume specific. 
so for example if you throw your "VM" image onto another completely separate device.. the SWAP file still resided on your system drive.
Which then impacts anything related to your OS & if your  system drive is an SSD...  then it really hammers the life and longevity of your SSD.. as you swap in & out huge volumes of data...

if you go to your "RCON" which is just the rust server address plus 8080, you can see your FPS rating.
Also I would recommend  throwing in "webmin" into your VM as well, which is available on port 10000

you can get some idea of what is possible with a decade old osx machine
when you start up your "rust" client BEFORE choosing a game, 
press F1 and in the console type "connect 61.92.40.144:28015"
