### ISSUE TITLE
New web rcon

### ISSUE THREAD

**Issue by cgarnier** [Didstopia/rust-server#7]
Hey,
I m working on a new webrcon app and wanted to share it with you.
It works as a docker container and the first release will have atleast the same features then the facepunch one.
I will publish it soon on github but you can try it there [http://rust-admin.com](http://rust-admin.com).
If  you are interrested about it, maybe i can make a PR with the docker-compose that allow to start a server with this webrcon ?

**Comment by cgarnier** [comment]
https://github.com/cgarnier/rust-admin

**Comment by Dids** [comment]
@cgarnier Thanks! I'll check it out and get back to you. :)

**Comment by Dids** [comment]
It would probably need minor modifications to work better as built-in service, mainly to dynamically set the connection IP and Port, instead of the user having to enter those each time.
I'm doing the same with FP's webrcon.

**Comment by edjayz** [comment]
nice work

**Comment by cgarnier** [comment]
Thanks for your feedback. Dont hesitate to post issue. I have already planned to add a banned list, an item giver, and force the server address.

**Comment by predominant** [comment]
Where do we want to go with this one? I think selecting a single rcon to include in the image is not a great way to go about it. Everyone has their own preferences.

I've spoken to @Dids about a separate container for the web rcon, with service dependencies, so any rcon into this container would be launched separately, thus decoupling the web from the core server itself.

Anyone else got some thoughts on that?
