### ISSUE TITLE
steam port?

### ISSUE THREAD

**Issue by Hardcore-fs** [Didstopia/rust-server#72]
during the load process

I see this:

Connecting anonymously to Steam Public...Generated client id: 3646959675019963547
Listening for IPv4 broadcast on: 27036

but there is no mapping to the outside of the docker container....
do we need one ?

**Comment by D0tty** [comment]
From [Speedguide.net](https://www.speedguide.net/port.php?port=27036): 
> 27031 udp, 27036 tcp/udp, and 27037 tcp (incoming for in-home streaming)

So you don't really need it no ;)
