### ISSUE TITLE
Issue with steamcmd on a previously working server

### ISSUE THREAD

**Issue by mnoblin792** [Didstopia/rust-server#73]
Hello all! I've been running this container in a Linux VM on my pc for a few weeks now for plugin testing. Upon booting up the VM today and attempting to use the server, I get the following

```Running as user: docker
Installing/updating steamcmd..
Installing or updating Rust.. (this might take a while, be patient)
Redirecting stderr to '/app/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
[  0%] Downloading update...
[  0%] Checking for available updates...
[----] !!! Fatal Error: Steamcmd needs to be online to update. Please confirm your network connection and try again.
threadtools.cpp (3655) : Assertion Failed: Illegal termination of worker thread 'Thread(0x0x56b68170/0x0xf79c0b'
Exiting, steamcmd install or update failed!
```

I didn't reconfigure anything. The only change to my knowledge is the new vehicles beta that began monday, so I guess that the client might need to update... ? But I'm just not sure what's caused this to start happening, be it some incompatibility with the container or something I've failed to configure properly. Here's my .env file for reference:

```RUST_SERVER_STARTUP_ARGUMENTS=-batchmode -load -nographics -logfiles /dev/null +server.secure 1

RUST_SERVER_IDENTITY=docker

RUST_SERVER_WORLDSIZE=4000

RUST_SERVER_SEED=20

RUST_SERVER_NAME=MyServer

RUST_SERVER_MAXPLAYERS=5

RUST_SERVER_DESCRIPTION=Let's make a server

RUST_RCON_PASSWORD=RconPassword

RUST_UPDATE_CHECKING=1

RUST_OXIDE_ENABLED=1
```

And the docker command I used to create the container:

`docker run --name rust-server -d -p 28015:28015 -p 28015:28015/udp -p 28016:28016 -p 8080:8080 -v /rust:/steamcmd/rust --env-file /rust.env didstopia/rust-server`

Again, I'm not sure what's caused this. I'm relatively new to the way GitHub works, so I apologize if this is an inappropriate place to ask for help on this. Thanks for any advice you can provide.

**Comment by Dids** [comment]
This seems like a host configuration issue (the linux VM in your case), as steamcmd doesn't seem to be able to connect to Steam. This might be a firewall issue, a host routing/networking/firewall issue or it might even be that Valve is blocking your hosting providers IPs.

**Comment by mnoblin792** [comment]
That was my initial thought. I've realized now I goofed a bit and forgot one detail that may be important. I had attempted to use the current staging branch for vehicles, aux01, and had reinitialized the container to run that branch. The VM only hosts the server, so that would be the only change between when the container was working and when it stopped. Spinning up a new VM and setting things up again seems to be running fine. Do you think there's a possibility the aux01 staging branch affected it in some way? Also, thanks for the reply!
