### ISSUE TITLE
Disconnected: connection attempt failed

### ISSUE THREAD

**Issue by MatteoInfi** [Didstopia/rust-server#74]
**Describe the bug**
I am using all defaults a part from port mappings and I cannot connect to my server even though **the server is online and appearing on my Steam server list**

**To Reproduce**

this is my port mapping: 

```

{
	ContainerPort: 28015,
	HostPort: 27015,
},
{
	ContainerPort: 28015,
	HostPort: 27001,
	Protocol: "udp",
},
{
	ContainerPort: 28016,
	HostPort: 27002,
},
{
	ContainerPort: 8080,
	HostPort:      27003,
},


```

Also I cannot connect to RCON getting `1006 error` with password `docker` as default

**Expected behavior**
Should connect

**Environment (please complete the following information):**
 - Host OS: Amazon Linux 2 4.14.181-140.257.amzn2.x86_64
 - `Docker version 19.03.6-ce, build 369ce74`

**Additional context**
The whole system is running on ECS

**Comment by MatteoInfi** [comment]
Ok, this is happening only if the servers is accessed through the UI or favorites, not if I use the steam console: `connect IP:PORT`

**Comment by MatteoInfi** [comment]
Ok, seems like it is a port problem. I have tried with the standard 28015 and it worked. However if I assign a random port between 27000 and 28000 (rather that 28015) it does not work.

Any help? Thanks

**Comment by MatteoInfi** [comment]
Ok, now this is easily reproducible, I have run a similar setup in localhost and I got the same exact problem

```
docker run --name rust-server -p 27091:28015 -p 27091:28015/udp -p 8081:8080 didstopia/rust-server

```

as well RCON is not connecting, but the server is still accessible through steam console

**Comment by MatteoInfi** [comment]
Well turns out that I am an idiot because I was not exposing `28016`, but strange that it wasn't working before. 

My bad and sorry for the monologue.

**Comment by MatteoInfi** [comment]
Ok, disregard my last message, this is still happening again

**Comment by danielsand** [comment]
@MatteoInfi do you use an EIP on your ECS ?
 i think its a NAT problem which append on the companion app introduction.
have the same problem on my baremetal k8s cluster and on a docker test machine.

**Comment by MatteoInfi** [comment]
@danielsand no, I have tried the same system in localhost and it does the same. So I exclude it is a problem coming from my system.

I have noticed that after 12/24 hours it actually works, I am not sure why though, maybe it takes 12/24 for steam to get the address?

**Comment by danielsand** [comment]
> @danielsand I have tried the same system in localhost and it does the same. So I exclude it is a problem coming from ECS
> 
> I have noticed that after 12/24 hours it actually works, I am not sure why though, maybe it takes 12/24 for steam to get the address from non standard ports?

my problem is gone now - but i have also discovered a DNS issues on my side which prevent my server from getting listed.

i have seen in last week facepunch release something interesting
> Change List 230
> Thursday, 4 June 2020
> " Added pairing with the companion app (make sure `app.port` isn't firewalled!)" 

so its working for me now.

**Comment by MatteoInfi** [comment]
@danielsand ok, thanks I will check this out again. BTW I have found this as well:

**Comment by MatteoInfi** [comment]
BTW I still cannot connect to RCON, any help?

**Comment by Dids** [comment]
Are you binding port `28016/tcp`? Could be any number of things, but usually a network issue outside of this specific image.

**Comment by Hardcore-fs** [comment]
seems you are not exporting the port.......

I see 28015   but i don't see 28016!!

**Comment by MatteoInfi** [comment]
> {
> 	ContainerPort: 28015,
> 	HostPort: 27015,
> },
> {
> 	ContainerPort: 28015,
> 	HostPort: 27001,
> 	Protocol: "udp",
> },
> {
> 	ContainerPort: 28016,
> 	HostPort: 27002,
> },
> {
> 	ContainerPort: 8080,
> 	HostPort:      27003,
> },

28016 is rcon

**Comment by Hardcore-fs** [comment]
so showed this:

 docker run --name rust-server -p 27091:28015 -p 27091:28015/udp -p 8081:8080 didstopia/rust-server

**Comment by MatteoInfi** [comment]
After that attempt I re-open it again, but it did not make any difference.

Oh, maybe I misunderstood, but you are talking about my RCON problem?

**Comment by Hardcore-fs** [comment]
you started a thread by saying "A",
you moved onto saying "B"
when an error with "B" was pointed out, you started talking about "C"

may I suggest you THROW AWAY everything so far and start fresh.

map the ports DIRECTLY
28015:28015
28016:28016
8080:8080

see if it works...

**Comment by Dids** [comment]
And if you wish to use different ports, set the env vars/launch arguments accordingly, so each port maps 1:1.
