### ISSUE TITLE
Container exits with no error

### ISSUE THREAD

**Issue by theshades** [Didstopia/rust-server#76]
**Describe the bug**
Not sure, but it just dies...

**To Reproduce**

╔═════════════════════════════════════════════════╗
║    _____  _     _     _              _          ║
║   |  __ \(_)   | |   | |            (_)         ║
║   | |  | |_  __| |___| |_ ___  _ __  _  __ _    ║
║   | |  | | |/ _| / __| __/ _ \| |_ \| |/ _| |   ║
║   | |__| | | (_| \__ \ || (_) | |_) | | (_| |   ║
║   |_____/|_|\__|_|___/\__\___/| |__/|_|\__|_|   ║
║                               | |               ║
║                               |_|               ║
╠═════════════════════════════════════════════════╣
║ You are using an image that is based on         ║
║ a base image maintained by Didstopia.           ║
║                                                 ║
║ For more information:                           ║
║ https://github.com/Didstopia/docker-base-images ║
╚═════════════════════════════════════════════════╝

Running as user: docker
Installing/updating steamcmd..
x linux32/
x linux32/libstdc++.so.6
x linux32/steamcmd
x steamcmd.sh
x steam.sh
Installing or updating Rust.. (this might take a while, be patient)
Redirecting stderr to '/app/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[  0%] Downloading update (0 of 76,908 KB)...
[  0%] Downloading update (5,497 of 76,908 KB)...
[  7%] Downloading update (10,165 of 76,908 KB)...
[ 13%] Downloading update (14,534 of 76,908 KB)...
[ 18%] Downloading update (18,654 of 76,908 KB)...
[ 24%] Downloading update (22,853 of 76,908 KB)...
[ 29%] Downloading update (26,753 of 76,908 KB)...
[ 34%] Downloading update (30,906 of 76,908 KB)...
[ 40%] Downloading update (35,081 of 76,908 KB)...
[ 45%] Downloading update (39,180 of 76,908 KB)...
[ 50%] Downloading update (43,117 of 76,908 KB)...
[ 56%] Downloading update (46,362 of 76,908 KB)...
[ 60%] Downloading update (48,582 of 76,908 KB)...
[ 63%] Downloading update (50,697 of 76,908 KB)...
[ 65%] Downloading update (52,816 of 76,908 KB)...
[ 68%] Downloading update (54,928 of 76,908 KB)...
[ 71%] Downloading update (57,308 of 76,908 KB)...
[ 74%] Downloading update (59,545 of 76,908 KB)...
[ 77%] Downloading update (61,654 of 76,908 KB)...
[ 80%] Downloading update (63,776 of 76,908 KB)...
[ 82%] Downloading update (65,875 of 76,908 KB)...
[ 85%] Downloading update (67,977 of 76,908 KB)...
[ 88%] Downloading update (70,245 of 76,908 KB)...
[ 91%] Downloading update (72,354 of 76,908 KB)...
[ 94%] Downloading update (74,298 of 76,908 KB)...
[ 96%] Downloading update (76,286 of 76,908 KB)...
[ 99%] Downloading update (76,908 of 76,908 KB)...
[100%] Download complete.
[----] Installing update...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Cleaning up...
[----] Update complete, launching %appname%...
Redirecting stderr to '/app/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Downloading update (162 of 51,248 KB)...
[  0%] Downloading update (4,263 of 51,248 KB)...
[  8%] Downloading update (6,997 of 51,248 KB)...
[ 13%] Downloading update (9,814 of 51,248 KB)...
[ 19%] Downloading update (12,232 of 51,248 KB)...
[ 23%] Downloading update (14,726 of 51,248 KB)...
[ 28%] Downloading update (17,211 of 51,248 KB)...
[ 33%] Downloading update (19,699 of 51,248 KB)...
[ 38%] Downloading update (22,163 of 51,248 KB)...
[ 43%] Downloading update (24,873 of 51,248 KB)...
[ 48%] Downloading update (27,240 of 51,248 KB)...
[ 53%] Downloading update (29,737 of 51,248 KB)...
[ 58%] Downloading update (31,586 of 51,248 KB)...
[ 61%] Downloading update (32,830 of 51,248 KB)...
[ 64%] Downloading update (34,071 of 51,248 KB)...
[ 66%] Downloading update (35,419 of 51,248 KB)...
[ 69%] Downloading update (36,625 of 51,248 KB)...
[ 71%] Downloading update (37,864 of 51,248 KB)...
[ 73%] Downloading update (39,072 of 51,248 KB)...
[ 76%] Downloading update (40,128 of 51,248 KB)...
[ 78%] Downloading update (41,492 of 51,248 KB)...
[ 80%] Downloading update (42,735 of 51,248 KB)...
[ 83%] Downloading update (43,984 of 51,248 KB)...
[ 85%] Downloading update (45,224 of 51,248 KB)...
[ 88%] Downloading update (46,406 of 51,248 KB)...
[ 90%] Downloading update (47,753 of 51,248 KB)...
[ 93%] Downloading update (48,997 of 51,248 KB)...
[ 95%] Downloading update (50,248 of 51,248 KB)...
[ 98%] Downloading update (51,248 of 51,248 KB)...
[100%] Download complete.
[----] Installing update...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Cleaning up...
[----] Update complete, launching Steamcmd...
Redirecting stderr to '/app/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...Warning: failed to init SDL thread priority manager: SDL not found
OK.
@sSteamCmdForcePlatformType linux
"@sSteamCmdForcePlatformType" = "linux"

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
force_install_dir /steamcmd/rust
app_info_update 1
app_update 258550 validate
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x5) verifying install, progress: 0.64 (35128134 / 5457706395)
 Update state (0x5) verifying install, progress: 8.79 (479724358 / 5457706395)
 Update state (0x5) verifying install, progress: 16.95 (924881939 / 5457706395)
 Update state (0x5) verifying install, progress: 25.17 (1373672467 / 5457706395)
 Update state (0x5) verifying install, progress: 33.47 (1826657299 / 5457706395)
 Update state (0x5) verifying install, progress: 41.65 (2273350675 / 5457706395)
 Update state (0x5) verifying install, progress: 49.84 (2719853684 / 5457706395)
 Update state (0x5) verifying install, progress: 57.90 (3160255604 / 5457706395)
 Update state (0x5) verifying install, progress: 66.17 (3611143284 / 5457706395)
 Update state (0x5) verifying install, progress: 73.92 (4034098560 / 5457706395)
 Update state (0x5) verifying install, progress: 81.91 (4470306176 / 5457706395)
 Update state (0x5) verifying install, progress: 89.86 (4904416640 / 5457706395)
 Update state (0x5) verifying install, progress: 97.15 (5302057226 / 5457706395)
 Update state (0x61) downloading, progress: 92.28 (6167040 / 6682624)
Success! App '258550' fully installed.
quit
Downloading and installing latest Oxide..
x RustDedicated_Data/
x RustDedicated_Data/Managed/
x RustDedicated_Data/Managed/Assembly-CSharp.dll
x RustDedicated_Data/Managed/Facepunch.Console.dll
x RustDedicated_Data/Managed/Facepunch.Network.dll
x RustDedicated_Data/Managed/Facepunch.Rcon.dll
x RustDedicated_Data/Managed/Mono.Data.Tds.dll
x RustDedicated_Data/Managed/MySql.Data.dll
x RustDedicated_Data/Managed/NewAssembly.dll
x RustDedicated_Data/Managed/Oxide.Core.dll
x RustDedicated_Data/Managed/Oxide.CSharp.dll
x RustDedicated_Data/Managed/Oxide.MySql.dll
x RustDedicated_Data/Managed/Oxide.References.dll
x RustDedicated_Data/Managed/Oxide.Rust.dll
x RustDedicated_Data/Managed/Oxide.SQLite.dll
x RustDedicated_Data/Managed/Oxide.Unity.dll
x RustDedicated_Data/Managed/System.Configuration.Install.dll
x RustDedicated_Data/Managed/System.Data.dll
x RustDedicated_Data/Managed/System.Data.SQLite.dll
x RustDedicated_Data/Managed/System.Drawing.dll
x RustDedicated_Data/Managed/System.Runtime.Serialization.dll
x RustDedicated_Data/Managed/System.Transactions.dll
x RustDedicated_Data/Managed/x64/
x RustDedicated_Data/Managed/x64/libmonoboehm-2.0.so.1
x RustDedicated_Data/Managed/x64/libMonoPosixHelper.so
x RustDedicated_Data/Managed/x64/libsqlite3
x RustDedicated_Data/Managed/x64/libsqlite3.so
x RustDedicated_Data/Managed/x64/sqlite3.dll
x RustDedicated_Data/Managed/x86/
x RustDedicated_Data/Managed/x86/libmonoboehm-2.0.so.1
x RustDedicated_Data/Managed/x86/libMonoPosixHelper.so
x RustDedicated_Data/Managed/x86/libsqlite3
x RustDedicated_Data/Managed/x86/libsqlite3.so
x RustDedicated_Data/Managed/x86/mono-2.0.dll
x RustDedicated_Data/Managed/x86/msvcp140.dll
x RustDedicated_Data/Managed/x86/msvcr120.dll
x RustDedicated_Data/Managed/x86/sqlite3.dll
Exiting, start mode is 1..

**Compose File**
version: '3'
services:
  rust-server:
    image: didstopia/rust-server
    ports:
      - "28015:28015"
      - "28016:28016"
      - "28082:28082"
    volumes:
      - .:/steamcmd/rust
    environment:
      RUST_SERVER_NAME: 'PMG WEST - LONG WIPE CITIES CHALLEGE SERVER'
      RUST_SERVER_SEED: 404
      RUST_SERVER_MAXPLAYERS: 175
      RUST_SERVER_DESCRIPTION: "Cities are safe zones (No PVP/PVE), outside of cities are the wild wild west of PVP! https://discord.me/penguinzmedia for support or issues! "
      RUST_SERVER_URL: "https://penguinzmedia.group/rust"
      RUST_RCON_PASSWORD: <redacted>
      RUST_UPDATE_CHECKING: 1
      RUST_START_MODE: 1
      RUST_OXIDE_ENABLED: 1
      RUST_OXIDE_UPDATE_ON_BOOT: 1
      RUST_SERVER_WORLDSIZE: 2000

**Environment (please complete the following information):**
 - OS:   lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

 - Docker: Docker version 19.03.12, build 48a66213fe
- Docker Compose: docker-compose version 1.17.1, build unknown
**Additional context**

Top:
top -n 1
top - 14:46:37 up  1:58,  1 user,  load average: 0.06, 0.18, 0.12
Tasks: 141 total,   1 running,  89 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.8 us,  0.2 sy,  0.0 ni, 98.9 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  8167560 total,  5245284 free,   526340 used,  2395936 buff/cache
KiB Swap:        0 total,        0 free,        0 used.  7343960 avail Mem

Free:
oot@app3:/opt/rustgame# free -h
              total        used        free      shared  buff/cache   available
Mem:           7.8G        513M        5.0G         13M        2.3G        7.0G
Swap:            0B          0B          0B

Error logs are empty.

**Comment by Dids** [comment]
You're using start mode 1, which updates and exits. 2 would skip update and start, while 0 (the default) both updates and starts the server.

**Comment by theshades** [comment]
Ahh, this wasnt clear from what I read... then again no sleep lately. will try that.
