### ISSUE TITLE
Server exiting at load

### ISSUE THREAD

**Issue by Maelep** [Didstopia/rust-server#78]
Docker Desktop MacOS: docker run --name rust-server -d -p 28015:28015 -p 28015:28015/udp -p 28016:28016 -p 8080:8080 --env-file rust.env didstopia/rust-server

`Asset Warmup (2837/6552)
Couldn't create a Convex Mesh from source mesh "ScrapHeliGibs_Part002" within the maximum polygons limit (256). The partial hull will be used. Consider simplifying your mesh.
Couldn't create a Convex Mesh from source mesh "ScrapHeliGibs_Part046" within the maximum polygons limit (256). The partial hull will be used. Consider simplifying your mesh.
Asset Warmup (3475/6552)
Asset Warmup (4106/6552)
HDR Render Texture not supported, disabling HDR on reflection probe.
Asset Warmup (4538/6552)
Asset Warmup (4967/6552)
Asset Warmup (5203/6552)
Asset Warmup (5569/6552)
Asset Warmup (5775/6552)
Asset Warmup (6025/6552)
Asset Warmup (6248/6552)
Asset Warmup (6378/6552)
Asset Warmup (6528/6552)
Asset Warmup (6552/6552)
WebSocket RCon Started on 28016
Generating procedural map of size 4500 with seed 658834
WARNING: Shader Unsupported: 'Hidden/Nature/Terrain/Utilities' - All passes removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
ERROR: Shader Shader is not supported on this GPU (none of subshaders/fallbacks are suitable)WARNING: Shader Unsupported: 'Hidden/Nature/Terrain/Utilities' - Setting to default shader.
Shader 'Nature/Terrain/Diffuse': dependency 'AddPassShader' shader 'Hidden/TerrainEngine/Splatmap/Diffuse-AddPass' not found
Shader 'Hidden/TerrainEngine/Splatmap/Standard-AddPass': fallback shader 'Hidden/TerrainEngine/Splatmap/Diffuse-AddPass' not found
[1.5s] Height Map
[1.2s] Topology Map
[0.4s] Splat Map
[1.4s] Road Ring
[6.7s] Harbors
[14.6s] Large Monuments
[8.4s] Medium Monuments
Exiting..`

**Comment by Dids** [comment]
How much memory do you have reserved for Docker? Rust needs at least 4GB to generate a default sized map.
If it runs out of memory, it exits exactly like this.

**Comment by Maelep** [comment]
My bad, forgot to change my RAM... Sorry.
I'm new to Docker. Where is located the rust-server folder? I would like to install some plugins.

**Comment by Dids** [comment]
You have to mount the `/steamcmd/rust` as a volume, then you can both persist the files as well as modify them.

**Comment by Maelep** [comment]
Thank you!
