### ISSUE TITLE
Console visual bug (small bug)

### ISSUE THREAD

**Issue by Maelep** [Didstopia/rust-server#79]
**Describe the bug**
The console show %appname% instead of Rust.

**To Reproduce**
Starts a server.

**Expected behavior**
Show Rust instead of % appname%.

**Screenshots**
`[----] Update complete, launching %appname%...`

**Environment (please complete the following information):**
 - OS: MacOS Docker Desktop
 - Docker: 19.03.12, build 48a66213fe

**Comment by Dids** [comment]
This seems to come from `steamcmd` itself, so not a bug with this image.
