### ISSUE TITLE
Vanilla servers uses - instead of +

### ISSUE THREAD

**Issue by brantje** [Didstopia/rust-server#8]
Not sure if this is true, but rad in a [reddit](https://www.reddit.com/r/playrust/comments/49od67/how_to_change_server_map_seed_and_size/d0tndiu/) comment that vanilla uses `-` instead of `+`

**Comment by Dids** [comment]
If you're referring to server parameters, then no, that's not true. There's an internal difference between `+` and `-`, and if I recall correctly, `+` arguments are console variables, meaning they're accessible in-game, while `-` parameters are handled by Unity/server.

**Comment by brantje** [comment]
Ah thanks for the heads up then.
