### ISSUE TITLE
Server doesn't enable (Unable to open log file, exiting)

### ISSUE THREAD

**Issue by CDFN** [Didstopia/rust-server#83]
**Describe the bug**
Server fails to run

**To Reproduce**
1. Run `docker run --name rust -d -p 28015:28015 -p 28015:28015/udp -p 28016:28016 -p 8080:8080 -v "${PWD}/rust:/steamcmd/rust" --env-file ./rust.env didstopia/rust-server` with 
```
RUST_SERVER_STARTUP_ARGUMENTS=-batchmode -load -logfile /dev/stdout +server.secure 1
RUST_SERVER_IDENTITY=cdfn_server
RUST_SERVER_SEED=123
RUST_SERVER_NAME=CDFN server
RUST_SERVER_DESCRIPTION=desc
RUST_RCON_PASSWORD=passwd
```
env file.
2. Wait some time until server downloads.
3. You should see https://hastebin.com/usokowazin.http error.

**Expected behavior**
Server enables successfully.

**Screenshots**
---

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.1
 - Docker: Docker version 19.03.13, build 4484c46d9d

**Additional context**
-

**Comment by Dids** [comment]
Remove `-logfile /dev/stdout` from `RUST_SERVER_STARTUP_ARGUMENTS` and do a `docker pull didstopia/rust-server:latest`, also use `didstopia/rust-server:latest` in your `docker run` command.

**Comment by CDFN** [comment]
Sorry for delay. It worked fine, thank you for quick support! :heart:
