### ISSUE TITLE
Last wiped date on forced wipe not updating

### ISSUE THREAD

**Issue by turowicz** [Didstopia/rust-server#84]
It seems that when the server wipes on forced wipe, the last wiped information is not updated. My server's current last wipe date is months ago as seen here: https://www.battlemetrics.com/servers/rust/7182479

Is this something that could be fixed?

**Comment by Software-Noob** [comment]
Nothing to do with the image, Rust, and websites like Battlemetrics detect a wipe based on the changed seed and entity count which sometimes can be faulty.

**Comment by turowicz** [comment]
Perhaps a setting that would randomly pick a seed on forced wipe?

**Comment by turowicz** [comment]
@Software-Noob ?

**Comment by Software-Noob** [comment]
Yes, that'd be one of the possible solutions, but that'd require a rewrite of the shell scripts to detect force wipe and change the seed at that time

**Comment by turowicz** [comment]
Currently the server process does automatically update. Perhaps this event could trigger the seed flush?

**Comment by turowicz** [comment]
cc @Dids
