### ISSUE TITLE
No RustDedicated_Data/Managed existing for me.

### ISSUE THREAD

**Issue by Tikomatura** [Didstopia/rust-server#89]
Well, I personally don't know too much about dockers, and such as our dev/host is taking care of that but recently I tried to install Rust: IO ( http://playrust.io/manual/#!index.md#Installation ) just as Discord Core ( https://umod.org/extensions/discord ). Quickly I came to a dead end. No RustDedicated_Data/Managed is existing. I asked my dev if he could build it in somehow as I might just have missing permissions to view folder x or y but he said those are actually just not existing while running through a docker. Now, we've been looking for a workaround for a while now but I finally decided to just ask here. 
Here's a screenshot from my view for reference https://i.imgur.com/CGv4vLS.png

I should also add that whenever I tell my dev that I had access to those folders on my previous host ( deinserverhost.de ), he tells me that he can't interfere with rusts source and deinserverhost probably has custom images and such setup. 

Does anyone know how to install such extensions on a docker? I'd be very grateful!

Btw, I don't really know anything about how to work with dockers/containers and such myself just yet. My dev is fully providing this service in form of game server hosting for me while I just take care of normal rust plugins, the players, etc. I'm sorry if the answer is obvious or this is the wrong category or such. I just kind of started to run out of options on how to improvise about certain things. That's how I ended up here. 

Sincerely,
-RustyMain
-Tikomatura

**Comment by Blastorios** [comment]
Hi Tikomatura,

If you use Didstopia's Image, the RustDedicated_Data/Managed directory is created automatically. If you can access your Docker instance through the command line, you will find it by doing:
```
user@somewhere: docker exec -it <instance name> /bin/bash
root@insidecontainer: cd steamcmd/rust/RustDedicated_Data/Managed
```

More conveniently, the directory you're looking for will be coupled to a locally accessible directory if you created a persistent volume (by simply providing a `-v ./path/to/local/volume:/steamcmd/rust` as described in the `readme`). `./path/to/local/volume` will now contain the exact same data as your Rust server is using.

Hope this clarifies some issues you're facing
