### ISSUE TITLE
Some users cannot connect

### ISSUE THREAD

**Issue by Fireant456** [Didstopia/rust-server#93]
I just set up the docker container via docker-compose and I am running into some odd behavior. I use CentOS 7 without any IPTables configuration and I am able to successfully connect to the server without issue. Some other players cannot find the server on the server list and cannot direct connect via the IP. The console will try connecting twice and say it does not receive a response.

**Comment by razorfish-sl** [comment]
well it's unlikely to be this.
Ive run this on centos 7 since last year....
