### ISSUE TITLE
https://rust.didscraft.com certificate error

### ISSUE THREAD

**Issue by cha0s** [Didstopia/rust-server#98]
Not a problem with the image, just that I got a cert error when visiting https://rust.didscraft.com/rust-server-on-linux-using-docker/ and thought you should know about it :)

**Comment by cha0s** [comment]
Wake up. Wake up. 

Wake up.

**Comment by Mambix** [comment]
they moved the website

**Comment by cha0s** [comment]
The website has not moved. The incorrect SSL certificate is provided.
